### ISSUE TITLE
AttributeError: 'BakeSettings' object has no attribute 'use_pass_subsurface'

### ISSUE THREAD

**Issue by form-follows-function** [Shahzod114/Blender-BakeLab2#2]
```
Traceback (most recent call last):
  File "/Users/home/Library/Application Support/Blender/2.83/scripts/addons/Blender-BakeLab2-master/bakelab_bake.py", line 818, in modal
    result = next(self.BakeCrt)
  File "/Users/home/Library/Application Support/Blender/2.83/scripts/addons/Blender-BakeLab2-master/bakelab_bake.py", line 610, in Bake
    self.save_defaults(context)
  File "/Users/home/Library/Application Support/Blender/2.83/scripts/addons/Blender-BakeLab2-master/bakelab_bake.py", line 76, in save_defaults
    self.default_use_pass_sss      = bake_settings.use_pass_subsurface
AttributeError: 'BakeSettings' object has no attribute 'use_pass_subsurface'

location: <unknown location>:-1
```

Baking fails regardless of which settings are used

**Comment by Shahzod114** [comment]
Just fixed

**Comment by form-follows-function** [comment]
Thanks!

**Comment by Paspartout** [comment]
Still getting a similar problem when trying to bake combined pass with blender 2.83.1:

```
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/home/paspartout/.config/blender/2.83/scripts/addons/Blender-BakeLab2-master/bakelab_bake.py", line 818, in modal
    result = next(self.BakeCrt)
  File "/home/paspartout/.config/blender/2.83/scripts/addons/Blender-BakeLab2-master/bakelab_bake.py", line 667, in Bake
    bake_type = self.init_bake_settings(context, map)
  File "/home/paspartout/.config/blender/2.83/scripts/addons/Blender-BakeLab2-master/bakelab_bake.py", line 349, in init_bake_settings
    bake_settings.use_pass_subsurface        = map.combined_subsurface
AttributeError: 'BakeSettings' object has no attribute 'use_pass_subsurface'

location: <unknown location>:-1
```

**Comment by Shahzod114** [comment]
@Paspartout  fixed
