### ISSUE TITLE
subclass error

### ISSUE THREAD

**Issue by RazwiMK** [Shahzod114/Blender-BakeLab2#23]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Win 10\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\Blender-BakeLab2-master\__init__.py", line 248, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'Baker'

**Comment by Gh0StCK** [comment]
I found a manual solution to this problem.
To reset BakeLab you need:

Go to the console (This is called Shift+F4)
In it write props = C.scene.BakeLabProps.
Then props.bake_state='NONE'
It is all! If the visible window has not changed its status, simply temporarily change the tab to any other one, and then go back to BakeLab.
